import type { ApiEndpoint } from '@/types/api-browser';

export const API_ENDPOINTS: ApiEndpoint[] = [
  // Events
  {
    id: 'get-events',
    name: 'Get Events',
    path: '/ext/events/summary/',
    method: 'GET',
    action: 'get',
    description: 'Retrieve all events for a section',
    category: 'events',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID to fetch events for',
        placeholder: '37458',
      },
      {
        name: 'termid',
        type: 'number',
        required: true,
        description: 'Term ID',
        placeholder: '842886',
      },
      {
        name: 'showArchived',
        type: 'select',
        required: false,
        description: 'Include archived events',
        default: 'false',
        options: ['true', 'false'],
      },
    ],
    exampleResponse: 'events.json',
  },
  {
    id: 'get-event-details',
    name: 'Get Event Details',
    path: '/v3/events/event/{eventid}/basic_details',
    method: 'GET',
    action: null,
    description: 'Get detailed information about a specific event',
    category: 'events',
    parameters: [
      {
        name: 'eventid',
        type: 'number',
        required: true,
        description: 'Event ID',
        placeholder: '1631576',
      },
    ],
    exampleResponse: 'event_details.json',
  },
  {
    id: 'get-event-summary',
    name: 'Get Event Summary',
    path: '/v3/events/event/{eventid}/summary',
    method: 'GET',
    action: null,
    description: 'Get event summary (v3 API)',
    category: 'events',
    parameters: [
      {
        name: 'eventid',
        type: 'number',
        required: true,
        description: 'Event ID',
        placeholder: '1631576',
      },
    ],
    exampleResponse: 'event_summary.json',
  },
  {
    id: 'get-event-attendance',
    name: 'Get Event Attendance',
    path: '/v3/events/event/{eventid}/members/attendance',
    method: 'GET',
    action: null,
    description: 'Get attendance records for an event',
    category: 'events',
    parameters: [
      {
        name: 'eventid',
        type: 'number',
        required: true,
        description: 'Event ID',
        placeholder: '1631576',
      },
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
    ],
    exampleResponse: 'attendance.json',
  },

  // Members
  {
    id: 'get-members',
    name: 'Get Members',
    path: '/ext/members/contact/',
    method: 'GET',
    action: 'getListOfMembers',
    description: 'Get all members in a section',
    category: 'members',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers', 'adults'],
        placeholder: 'explorers',
      },
    ],
    exampleResponse: 'members.json',
  },
  {
    id: 'get-patrols',
    name: 'Get Patrols',
    path: '/ext/members/patrols/',
    method: 'GET',
    action: 'getPatrolsWithPeople',
    description: 'Get patrol structure for a section',
    category: 'members',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
    ],
    exampleResponse: 'patrols.json',
  },

  // Badges
  {
    id: 'get-badges',
    name: 'Get Badges',
    path: '/ext/badges/records/',
    method: 'GET',
    action: 'getBadgeStructure',
    description: 'Get all available badges for a section',
    category: 'badges',
    parameters: [
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'term_id',
        type: 'number',
        required: true,
        description: 'Term ID',
        placeholder: '12345',
      },
    ],
    exampleResponse: 'badges.json',
  },
  {
    id: 'get-badge-records',
    name: 'Get Badge Records',
    path: '/ext/badges/records/',
    method: 'GET',
    action: 'getBadgeRecords',
    description: 'Get badge progress for all members',
    category: 'badges',
    parameters: [
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'term_id',
        type: 'number',
        required: true,
        description: 'Term ID',
        placeholder: '12345',
      },
      {
        name: 'badge_id',
        type: 'number',
        required: true,
        description: 'Badge ID',
        placeholder: '1',
      },
    ],
    exampleResponse: 'badge_records.json',
  },

  // Flexi Records
  {
    id: 'get-flexi-structure',
    name: 'Get Flexi Record Structure',
    path: '/ext/customrecords/records/',
    method: 'GET',
    action: 'getStructure',
    description: 'Get structure of custom flexi record columns',
    category: 'other',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
    ],
    exampleResponse: 'flexi_structure.json',
  },
  {
    id: 'get-flexi-data',
    name: 'Get Flexi Record Data',
    path: '/ext/customrecords/records/',
    method: 'GET',
    action: 'getRecordData',
    description: 'Get data for a specific flexi record',
    category: 'other',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
      {
        name: 'recordid',
        type: 'number',
        required: true,
        description: 'Flexi Record ID',
        placeholder: '123',
      },
    ],
    exampleResponse: 'flexi_data.json',
  },

  // Quartermaster
  {
    id: 'get-qm-lists',
    name: 'Get Quartermaster Lists',
    path: '/ext/quartermaster/',
    method: 'GET',
    action: 'getListOfLists',
    description: 'Get all quartermaster lists for a section',
    category: 'quartermaster',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
    ],
    exampleResponse: 'listOfQMLists.json',
  },
  {
    id: 'get-qm-list',
    name: 'Get Quartermaster List',
    path: '/ext/quartermaster/',
    method: 'GET',
    action: 'getList',
    description: 'Get items in a specific quartermaster list',
    category: 'quartermaster',
    parameters: [
      {
        name: 'sectionid',
        type: 'number',
        required: true,
        description: 'Section ID',
        placeholder: '37458',
      },
      {
        name: 'section',
        type: 'select',
        required: true,
        description: 'Section type',
        options: ['beavers', 'cubs', 'scouts', 'explorers'],
        placeholder: 'explorers',
      },
      {
        name: 'listid',
        type: 'number',
        required: true,
        description: 'List ID',
        placeholder: '456',
      },
    ],
    exampleResponse: 'QMList.json',
  },

  // Generic
  {
    id: 'get-startup-config',
    name: 'Get Startup Config',
    path: '/ext/generic/startup/',
    method: 'GET',
    action: 'getConfig',
    description: 'Get application startup configuration',
    category: 'generic',
    parameters: [],
    exampleResponse: 'startup_config.json',
  },
];

export const API_CATEGORIES = [
  { value: 'all', label: 'All Endpoints' },
  { value: 'events', label: 'Events' },
  { value: 'members', label: 'Members' },
  { value: 'badges', label: 'Badges' },
  { value: 'quartermaster', label: 'Quartermaster' },
  { value: 'generic', label: 'Generic' },
  { value: 'other', label: 'Other' },
] as const;
